# Generated by Django 5.0.6 on 2024-05-14 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_stocks', '0003_remove_userprofile_cash_balance_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='position',
            name='stock',
        ),
        migrations.AddField(
            model_name='position',
            name='stock_symbol',
            field=models.CharField(default=None, max_length=50),
            preserve_default=False,
        ),
    ]
